name: pipelinewithkhansh
schedules:
  - cron: '13 23 1 11 5'               # Runs daily at midnight UTC
    displayName: 'Daily Midnight Build'
    branches:
      include:
        - main                      # Trigger only for 'main' branch
    always: true 
pool: autopool
stages:
  - stage: terraforminstall
    jobs:
      - job: tnstallinit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'autopool'
            backendAzureRmResourceGroupName: 'forpipeline'
            backendAzureRmStorageAccountName: 'mypipelinestorage'
            backendAzureRmContainerName: 'pipelinecontainer'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'autopool'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'autopool'